//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalCompany.PersonalProduct.Utility.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpurSol.Xoopah.Utility.Messages.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acccount Succesfully Created..
        /// </summary>
        public static string AccountCreated {
            get {
                return ResourceManager.GetString("AccountCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acccount Creation Failed!.
        /// </summary>
        public static string AccountCreationFailed {
            get {
                return ResourceManager.GetString("AccountCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account is not connected with any Google account!.
        /// </summary>
        public static string AccountNotConnectedWithGoogle {
            get {
                return ResourceManager.GetString("AccountNotConnectedWithGoogle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address can&apos;t exceed more than 200 characters..
        /// </summary>
        public static string AddressLength {
            get {
                return ResourceManager.GetString("AddressLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string AdminRole {
            get {
                return ResourceManager.GetString("AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No blocked contacts exist..
        /// </summary>
        public static string BlockedContactDoesNotExist {
            get {
                return ResourceManager.GetString("BlockedContactDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking successfully added..
        /// </summary>
        public static string BookingAdded {
            get {
                return ResourceManager.GetString("BookingAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking archived successfully..
        /// </summary>
        public static string BookingArchived {
            get {
                return ResourceManager.GetString("BookingArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking could not be archived!.
        /// </summary>
        public static string BookingArchiveFailed {
            get {
                return ResourceManager.GetString("BookingArchiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking successfully Deleted..
        /// </summary>
        public static string BookingDeleted {
            get {
                return ResourceManager.GetString("BookingDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Deleted from Google Calendar..
        /// </summary>
        public static string BookingDeletedFromGoogleCalendar {
            get {
                return ResourceManager.GetString("BookingDeletedFromGoogleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking couldn&apos;t be Deleted!.
        /// </summary>
        public static string BookingDeletionFailed {
            get {
                return ResourceManager.GetString("BookingDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking does not exist..
        /// </summary>
        public static string BookingDoesNotExist {
            get {
                return ResourceManager.GetString("BookingDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking could not be added!.
        /// </summary>
        public static string BookingFailed {
            get {
                return ResourceManager.GetString("BookingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add a booking because your contact&apos;s limit is breached..
        /// </summary>
        public static string BookingNotCreatedDueToContactsLimit {
            get {
                return ResourceManager.GetString("BookingNotCreatedDueToContactsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bookings found for this Business..
        /// </summary>
        public static string BookingNotFoundAgainstBusinessId {
            get {
                return ResourceManager.GetString("BookingNotFoundAgainstBusinessId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking couldn&apos;t be Restored!.
        /// </summary>
        public static string BookingNotRestored {
            get {
                return ResourceManager.GetString("BookingNotRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking couldn&apos;t be updated..
        /// </summary>
        public static string BookingNotUpdated {
            get {
                return ResourceManager.GetString("BookingNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking successfully Restored..
        /// </summary>
        public static string BookingRestored {
            get {
                return ResourceManager.GetString("BookingRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking(s) successfully Archived..
        /// </summary>
        public static string BookingsArchived {
            get {
                return ResourceManager.GetString("BookingsArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking(s) successfully marked as Confirmed..
        /// </summary>
        public static string BookingsConfirmed {
            get {
                return ResourceManager.GetString("BookingsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking(s) successfully Deleted..
        /// </summary>
        public static string BookingsDeleted {
            get {
                return ResourceManager.GetString("BookingsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To add more bookings, please upgrade your package..
        /// </summary>
        public static string BookingsLimitReached {
            get {
                return ResourceManager.GetString("BookingsLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking updated successfully..
        /// </summary>
        public static string BookingUpdated {
            get {
                return ResourceManager.GetString("BookingUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking updated in Google Calendar..
        /// </summary>
        public static string BookingUpdatedInGoogleCalendar {
            get {
                return ResourceManager.GetString("BookingUpdatedInGoogleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts could not be Archived!.
        /// </summary>
        public static string BulkArchiveContactsFailed {
            get {
                return ResourceManager.GetString("BulkArchiveContactsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All contacts Archived successfully..
        /// </summary>
        public static string BulkArchiveContactsSuccessful {
            get {
                return ResourceManager.GetString("BulkArchiveContactsSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users couldn&apos;t be deleted!.
        /// </summary>
        public static string BulkBusinessUserDeleteFailed {
            get {
                return ResourceManager.GetString("BulkBusinessUserDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users are successfully deleted..
        /// </summary>
        public static string BulkBusinessUserDeleteSuccessful {
            get {
                return ResourceManager.GetString("BulkBusinessUserDeleteSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts Groups deleted successfully..
        /// </summary>
        public static string BulkContactGroupsDeleted {
            get {
                return ResourceManager.GetString("BulkContactGroupsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Groups couldn&apos;t be deleted!.
        /// </summary>
        public static string BulkContactGroupsNotDeleted {
            get {
                return ResourceManager.GetString("BulkContactGroupsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts could not be deleted!.
        /// </summary>
        public static string BulkDeleteContactsFailed {
            get {
                return ResourceManager.GetString("BulkDeleteContactsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts succesfully deleted..
        /// </summary>
        public static string BulkDeleteContactsSucessful {
            get {
                return ResourceManager.GetString("BulkDeleteContactsSucessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Groups deleted successfylly..
        /// </summary>
        public static string BulkUserGroupsDeleted {
            get {
                return ResourceManager.GetString("BulkUserGroupsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Group could not be deleted!.
        /// </summary>
        public static string BulkUserGroupsNotDeleted {
            get {
                return ResourceManager.GetString("BulkUserGroupsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address could not be updated!.
        /// </summary>
        public static string BusinessAddressNotUpdated {
            get {
                return ResourceManager.GetString("BusinessAddressNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business address updated successfully..
        /// </summary>
        public static string BusinessAddressUpdated {
            get {
                return ResourceManager.GetString("BusinessAddressUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Contact created successfully..
        /// </summary>
        public static string BusinessContactCreated {
            get {
                return ResourceManager.GetString("BusinessContactCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Contact couldn&apos;t be created!.
        /// </summary>
        public static string BusinessContactCreationFailed {
            get {
                return ResourceManager.GetString("BusinessContactCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business contact successfully deleted..
        /// </summary>
        public static string BusinessContactDeleted {
            get {
                return ResourceManager.GetString("BusinessContactDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business contact could not be deleted!.
        /// </summary>
        public static string BusinessContactDeletionFailed {
            get {
                return ResourceManager.GetString("BusinessContactDeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business contact could not be updated!.
        /// </summary>
        public static string BusinessContactNotUpdated {
            get {
                return ResourceManager.GetString("BusinessContactNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business contact updated successfully..
        /// </summary>
        public static string BusinessContactUpdated {
            get {
                return ResourceManager.GetString("BusinessContactUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business created successfully..
        /// </summary>
        public static string BusinessCreated {
            get {
                return ResourceManager.GetString("BusinessCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business could not be created!.
        /// </summary>
        public static string BusinessCreationFailed {
            get {
                return ResourceManager.GetString("BusinessCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business deleted successfully..
        /// </summary>
        public static string BusinessDeleted {
            get {
                return ResourceManager.GetString("BusinessDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business details could not be updated!.
        /// </summary>
        public static string BusinessDetailsNotUpdated {
            get {
                return ResourceManager.GetString("BusinessDetailsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business details updated successfully..
        /// </summary>
        public static string BusinessDetailsUpdated {
            get {
                return ResourceManager.GetString("BusinessDetailsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email template successfully created..
        /// </summary>
        public static string BusinessEmailTemplateAdded {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template deleted..
        /// </summary>
        public static string BusinessEmailTemplateDeleted {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template disabled..
        /// </summary>
        public static string BusinessEmailTemplateDisabled {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template enabled..
        /// </summary>
        public static string BusinessEmailTemplateEnabled {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add new email template!.
        /// </summary>
        public static string BusinessEmailTemplateNotAdded {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template could not be deleted!.
        /// </summary>
        public static string BusinessEmailTemplateNotDeleted {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template could not be disabled!.
        /// </summary>
        public static string BusinessEmailTemplateNotDisabled {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateNotDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template could not be enabled!.
        /// </summary>
        public static string BusinessEmailTemplateNotEnabled {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template does not exist!.
        /// </summary>
        public static string BusinessEmailTemplateNotFound {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template couldn&apos;t be updated!.
        /// </summary>
        public static string BusinessEmailTemplateNotUpdated {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no saved Business Email Templates!.
        /// </summary>
        public static string BusinessEmailTemplatesNotFound {
            get {
                return ResourceManager.GetString("BusinessEmailTemplatesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Template updated successfully..
        /// </summary>
        public static string BusinessEmailTemplateUpdated {
            get {
                return ResourceManager.GetString("BusinessEmailTemplateUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business linked successfully..
        /// </summary>
        public static string BusinessLinked {
            get {
                return ResourceManager.GetString("BusinessLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business listed successfully..
        /// </summary>
        public static string BusinessListed {
            get {
                return ResourceManager.GetString("BusinessListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Business Name {{BUSINESS_NAME}} is already in use. Kindly choose a unique one for you..
        /// </summary>
        public static string BusinessNameAlreadyExists {
            get {
                return ResourceManager.GetString("BusinessNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business name can&apos;t be empty..
        /// </summary>
        public static string BusinessNameNotEmpty {
            get {
                return ResourceManager.GetString("BusinessNameNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business could not be deleted!.
        /// </summary>
        public static string BusinessNotDeleted {
            get {
                return ResourceManager.GetString("BusinessNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business not found..
        /// </summary>
        public static string BusinessNotFound {
            get {
                return ResourceManager.GetString("BusinessNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business linking failed!.
        /// </summary>
        public static string BusinessNotLinked {
            get {
                return ResourceManager.GetString("BusinessNotLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business listing failed!.
        /// </summary>
        public static string BusinessNotListed {
            get {
                return ResourceManager.GetString("BusinessNotListed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business information could not be updated!.
        /// </summary>
        public static string BusinessNotUpdated {
            get {
                return ResourceManager.GetString("BusinessNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product created successfully..
        /// </summary>
        public static string BusinessProductCreated {
            get {
                return ResourceManager.GetString("BusinessProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product deleted..
        /// </summary>
        public static string BusinessProductDeleted {
            get {
                return ResourceManager.GetString("BusinessProductDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product does not exist..
        /// </summary>
        public static string BusinessProductDoesNotExist {
            get {
                return ResourceManager.GetString("BusinessProductDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product could not be created..
        /// </summary>
        public static string BusinessProductNotCreated {
            get {
                return ResourceManager.GetString("BusinessProductNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product could not be deleted!.
        /// </summary>
        public static string BusinessProductNotDeleted {
            get {
                return ResourceManager.GetString("BusinessProductNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product could not be updated!.
        /// </summary>
        public static string BusinessProductNotUpdated {
            get {
                return ResourceManager.GetString("BusinessProductNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Product updated successfully..
        /// </summary>
        public static string BusinessProductUpdated {
            get {
                return ResourceManager.GetString("BusinessProductUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service created successfully..
        /// </summary>
        public static string BusinessServiceCreated {
            get {
                return ResourceManager.GetString("BusinessServiceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service deleted successfully..
        /// </summary>
        public static string BusinessServiceDeleted {
            get {
                return ResourceManager.GetString("BusinessServiceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service does not exist..
        /// </summary>
        public static string BusinessServiceDoesNotExist {
            get {
                return ResourceManager.GetString("BusinessServiceDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service could not be created!.
        /// </summary>
        public static string BusinessServiceNotCreated {
            get {
                return ResourceManager.GetString("BusinessServiceNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service could not be deleted!.
        /// </summary>
        public static string BusinessServiceNotDeleted {
            get {
                return ResourceManager.GetString("BusinessServiceNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t add a repeated service. Please choose a unique name..
        /// </summary>
        public static string BusinessServiceNotUnique {
            get {
                return ResourceManager.GetString("BusinessServiceNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service could not be updated!.
        /// </summary>
        public static string BusinessServiceNotUpdated {
            get {
                return ResourceManager.GetString("BusinessServiceNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Service updated successfully..
        /// </summary>
        public static string BusinessServiceUpdated {
            get {
                return ResourceManager.GetString("BusinessServiceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business information updated successfully..
        /// </summary>
        public static string BusinessUpdated {
            get {
                return ResourceManager.GetString("BusinessUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User successfully added to the Group(s)..
        /// </summary>
        public static string BusinessUserAddedToGroup {
            get {
                return ResourceManager.GetString("BusinessUserAddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User created successfully..
        /// </summary>
        public static string BusinessUserCreated {
            get {
                return ResourceManager.GetString("BusinessUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User deleted..
        /// </summary>
        public static string BusinessUserDeleted {
            get {
                return ResourceManager.GetString("BusinessUserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User does not exist..
        /// </summary>
        public static string BusinessUserDoesNotExist {
            get {
                return ResourceManager.GetString("BusinessUserDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group successfully created..
        /// </summary>
        public static string BusinessUserGroupCreated {
            get {
                return ResourceManager.GetString("BusinessUserGroupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group deleted..
        /// </summary>
        public static string BusinessUserGroupDeleted {
            get {
                return ResourceManager.GetString("BusinessUserGroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group does not exist..
        /// </summary>
        public static string BusinessUserGroupDoesNotExist {
            get {
                return ResourceManager.GetString("BusinessUserGroupDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group could not be created!.
        /// </summary>
        public static string BusinessUserGroupNotCreated {
            get {
                return ResourceManager.GetString("BusinessUserGroupNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group could not be deleted!.
        /// </summary>
        public static string BusinessUserGroupNotDeleted {
            get {
                return ResourceManager.GetString("BusinessUserGroupNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group could not be updated!.
        /// </summary>
        public static string BusinessUserGroupNotUpdated {
            get {
                return ResourceManager.GetString("BusinessUserGroupNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User Group successfully updated..
        /// </summary>
        public static string BusinessUserGroupUpdated {
            get {
                return ResourceManager.GetString("BusinessUserGroupUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User could not be added to the Group(s)!.
        /// </summary>
        public static string BusinessUserNotAddedToGroup {
            get {
                return ResourceManager.GetString("BusinessUserNotAddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User could not be created!.
        /// </summary>
        public static string BusinessUserNotCreated {
            get {
                return ResourceManager.GetString("BusinessUserNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User could not be deleted!.
        /// </summary>
        public static string BusinessUserNotDeleted {
            get {
                return ResourceManager.GetString("BusinessUserNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User could not be updated!.
        /// </summary>
        public static string BusinessUserNotUpdated {
            get {
                return ResourceManager.GetString("BusinessUserNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To add more users, please upgrade your package..
        /// </summary>
        public static string BusinessUsersLimitReached {
            get {
                return ResourceManager.GetString("BusinessUsersLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business group has been created but we couldn&apos;t add the users in it. Kindly add users from the users grid..
        /// </summary>
        public static string BusinessUsersNotAddedInGroup {
            get {
                return ResourceManager.GetString("BusinessUsersNotAddedInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Group successfully deleted but users could not be removed from group!.
        /// </summary>
        public static string BusinessUsersNotDeletedFromGroup {
            get {
                return ResourceManager.GetString("BusinessUsersNotDeletedFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business User updated successfully..
        /// </summary>
        public static string BusinessUserUpdated {
            get {
                return ResourceManager.GetString("BusinessUserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your calendar has been successfully synced..
        /// </summary>
        public static string CalendarSyncedSuccessfully {
            get {
                return ResourceManager.GetString("CalendarSyncedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Synchorization Failed..
        /// </summary>
        public static string CalendarSyncFailed {
            get {
                return ResourceManager.GetString("CalendarSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card successfully charged..
        /// </summary>
        public static string CardCharged {
            get {
                return ResourceManager.GetString("CardCharged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category can&apos;t be empty..
        /// </summary>
        public static string CategoryNotEmpty {
            get {
                return ResourceManager.GetString("CategoryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City name can&apos;t exceed more than 50 characters..
        /// </summary>
        public static string CityNameLength {
            get {
                return ResourceManager.GetString("CityNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact added successfully..
        /// </summary>
        public static string ContactAdded {
            get {
                return ResourceManager.GetString("ContactAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully added to group(s)..
        /// </summary>
        public static string ContactAddedToGroup {
            get {
                return ResourceManager.GetString("ContactAddedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is already blocked..
        /// </summary>
        public static string ContactAlreadyBlocked {
            get {
                return ResourceManager.GetString("ContactAlreadyBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contact you are trying to add already exists..
        /// </summary>
        public static string ContactAlreadyExists {
            get {
                return ResourceManager.GetString("ContactAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact is already not blocked..
        /// </summary>
        public static string ContactAlreadyNotBlocked {
            get {
                return ResourceManager.GetString("ContactAlreadyNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully Archived..
        /// </summary>
        public static string ContactArchived {
            get {
                return ResourceManager.GetString("ContactArchived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be Archived!.
        /// </summary>
        public static string ContactArchiveFailed {
            get {
                return ResourceManager.GetString("ContactArchiveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully blocked..
        /// </summary>
        public static string ContactBlocked {
            get {
                return ResourceManager.GetString("ContactBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact deleted successfully..
        /// </summary>
        public static string ContactDeleted {
            get {
                return ResourceManager.GetString("ContactDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully removed from group(s)..
        /// </summary>
        public static string ContactDeletedFromGroup {
            get {
                return ResourceManager.GetString("ContactDeletedFromGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact does not exist..
        /// </summary>
        public static string ContactDoesNotExist {
            get {
                return ResourceManager.GetString("ContactDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group added successfully..
        /// </summary>
        public static string ContactGroupAdded {
            get {
                return ResourceManager.GetString("ContactGroupAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group deleted successfully..
        /// </summary>
        public static string ContactGroupDeleted {
            get {
                return ResourceManager.GetString("ContactGroupDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group could not be added!.
        /// </summary>
        public static string ContactGroupNotAdded {
            get {
                return ResourceManager.GetString("ContactGroupNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group could not be deleted!.
        /// </summary>
        public static string ContactGroupNotDeleted {
            get {
                return ResourceManager.GetString("ContactGroupNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group not found!.
        /// </summary>
        public static string ContactGroupNotFound {
            get {
                return ResourceManager.GetString("ContactGroupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group could not be updated!.
        /// </summary>
        public static string ContactGroupNotUpdated {
            get {
                return ResourceManager.GetString("ContactGroupNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Group updated successfully..
        /// </summary>
        public static string ContactGroupUpdated {
            get {
                return ResourceManager.GetString("ContactGroupUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be added!.
        /// </summary>
        public static string ContactNotAdded {
            get {
                return ResourceManager.GetString("ContactNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be blocked!.
        /// </summary>
        public static string ContactNotBlocked {
            get {
                return ResourceManager.GetString("ContactNotBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be deleted!.
        /// </summary>
        public static string ContactNotDeleted {
            get {
                return ResourceManager.GetString("ContactNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact not found..
        /// </summary>
        public static string ContactNotFound {
            get {
                return ResourceManager.GetString("ContactNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be blocked!.
        /// </summary>
        public static string ContactNotUnblocked {
            get {
                return ResourceManager.GetString("ContactNotUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be updated!.
        /// </summary>
        public static string ContactNotUpdated {
            get {
                return ResourceManager.GetString("ContactNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact could not be Restored!.
        /// </summary>
        public static string ContactRestorationFailed {
            get {
                return ResourceManager.GetString("ContactRestorationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully Restored..
        /// </summary>
        public static string ContactRestored {
            get {
                return ResourceManager.GetString("ContactRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts successfully assigned to group..
        /// </summary>
        public static string ContactsAssignedToGroup {
            get {
                return ResourceManager.GetString("ContactsAssignedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{CONTACT_COUNT}} contacts in this group don&apos;t have Emails..
        /// </summary>
        public static string ContactsHaveNoEmail {
            get {
                return ResourceManager.GetString("ContactsHaveNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{CONTACT_COUNT}} contacts in this group don&apos;t have Phone Numbers..
        /// </summary>
        public static string ContactsHaveNoNumber {
            get {
                return ResourceManager.GetString("ContactsHaveNoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts successfully imported from Gmail..
        /// </summary>
        public static string ContactsImportedFromGmail {
            get {
                return ResourceManager.GetString("ContactsImportedFromGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since you have a {{PACKAGE_NAME}} subscription, only the first {{CONTACTS_COUNT}} contacts were added..
        /// </summary>
        public static string ContactsImportMessageForPackage {
            get {
                return ResourceManager.GetString("ContactsImportMessageForPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To add more contacts, please upgrade your package..
        /// </summary>
        public static string ContactsLimitReached {
            get {
                return ResourceManager.GetString("ContactsLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact(s) successfully marked as Favorite..
        /// </summary>
        public static string ContactsMarkedAsFavorite {
            get {
                return ResourceManager.GetString("ContactsMarkedAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact(s) successfully unmarked as Favorite..
        /// </summary>
        public static string ContactsMarkedAsNonFavorite {
            get {
                return ResourceManager.GetString("ContactsMarkedAsNonFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts couldn&apos;t be assigned to group..
        /// </summary>
        public static string ContactsNotAssignedToGroup {
            get {
                return ResourceManager.GetString("ContactsNotAssignedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts could not be imported from Gmail!.
        /// </summary>
        public static string ContactsNotImportedFromGmail {
            get {
                return ResourceManager.GetString("ContactsNotImportedFromGmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact(s) couldn&apos;t be marked as Favorite!.
        /// </summary>
        public static string ContactsNotMarkedAsFavorite {
            get {
                return ResourceManager.GetString("ContactsNotMarkedAsFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact(s) couldn&apos;t be unmarked as Favorite!.
        /// </summary>
        public static string ContactsNotMarkedAsNonFavorite {
            get {
                return ResourceManager.GetString("ContactsNotMarkedAsNonFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts couldn&apos;t be restored!.
        /// </summary>
        public static string ContactsNotRestored {
            get {
                return ResourceManager.GetString("ContactsNotRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts successfully restored..
        /// </summary>
        public static string ContactsRestored {
            get {
                return ResourceManager.GetString("ContactsRestored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact unblocked successfully..
        /// </summary>
        public static string ContactUnblocked {
            get {
                return ResourceManager.GetString("ContactUnblocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact updated successfully..
        /// </summary>
        public static string ContactUpdated {
            get {
                return ResourceManager.GetString("ContactUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country field must not be empty..
        /// </summary>
        public static string CountryNotEmpty {
            get {
                return ResourceManager.GetString("CountryNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County must not be empty..
        /// </summary>
        public static string CountyNotEmpty {
            get {
                return ResourceManager.GetString("CountyNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisp Settings Added.
        /// </summary>
        public static string CrispSettingsAdded {
            get {
                return ResourceManager.GetString("CrispSettingsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crisp Settings Updated.
        /// </summary>
        public static string CrispSettingsUpdated {
            get {
                return ResourceManager.GetString("CrispSettingsUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts successfully imported from file..
        /// </summary>
        public static string CSVContactsImported {
            get {
                return ResourceManager.GetString("CSVContactsImported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day cannot be empty..
        /// </summary>
        public static string DayNotEmpty {
            get {
                return ResourceManager.GetString("DayNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a default template of &apos;Payment&apos; type!.
        /// </summary>
        public static string DefaultPaymentTemplateNotFound {
            get {
                return ResourceManager.GetString("DefaultPaymentTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description can&apos;t exceed more than 750 characters..
        /// </summary>
        public static string DescriptionLength {
            get {
                return ResourceManager.GetString("DescriptionLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided Business User Email is already in use. Kindly provide a unique one..
        /// </summary>
        public static string EmailAlreadyExists {
            get {
                return ResourceManager.GetString("EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided email does not exist..
        /// </summary>
        public static string EmailDoesNotExist {
            get {
                return ResourceManager.GetString("EmailDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is invalid!.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To send more emails, please upgrade your package..
        /// </summary>
        public static string EmailLimitReached {
            get {
                return ResourceManager.GetString("EmailLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email succesfully sent..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Campaign couldn&apos;t be sent!.
        /// </summary>
        public static string EmailsNotSent {
            get {
                return ResourceManager.GetString("EmailsNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Campaign shooted successfully.
        /// </summary>
        public static string EmailsSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailsSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re receiving this email because you signed up for updates about Xoopah Platform..
        /// </summary>
        public static string EmailSubscriptionMessage {
            get {
                return ResourceManager.GetString("EmailSubscriptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured, please try again later..
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add Crisp Settings.
        /// </summary>
        public static string FailedToAddCrispSettings {
            get {
                return ResourceManager.GetString("FailedToAddCrispSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update Crisp Settings.
        /// </summary>
        public static string FailedToUpdateCrispSettings {
            get {
                return ResourceManager.GetString("FailedToUpdateCrispSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email has been sent to you at {{USER_EMAIL}}. Please click the link in the email to start the password change process..
        /// </summary>
        public static string ForgotPasswordEmailSent {
            get {
                return ResourceManager.GetString("ForgotPasswordEmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Encountered. Please try again later!.
        /// </summary>
        public static string GMBConnectionNotRemoved {
            get {
                return ResourceManager.GetString("GMBConnectionNotRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google My Business connection removed..
        /// </summary>
        public static string GMBConnectionRemoved {
            get {
                return ResourceManager.GetString("GMBConnectionRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ITEM_NAME}} could not be imported!.
        /// </summary>
        public static string ImportFailed {
            get {
                return ResourceManager.GetString("ImportFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {{ITEM_NAME}} successfully imported..
        /// </summary>
        public static string ImportSuccessful {
            get {
                return ResourceManager.GetString("ImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiries(s) Deleted Successfully..
        /// </summary>
        public static string InquiriesDeleted {
            get {
                return ResourceManager.GetString("InquiriesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquirie(s) couldn&apos;t be deleted!.
        /// </summary>
        public static string InquiriesNotDeleted {
            get {
                return ResourceManager.GetString("InquiriesNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry added Successfully..
        /// </summary>
        public static string InquiryAdded {
            get {
                return ResourceManager.GetString("InquiryAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry successfully Deleted..
        /// </summary>
        public static string InquiryDeleted {
            get {
                return ResourceManager.GetString("InquiryDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry could not be added!.
        /// </summary>
        public static string InquiryNotAdded {
            get {
                return ResourceManager.GetString("InquiryNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry couldn&apos;t be Deleted!.
        /// </summary>
        public static string InquiryNotDeleted {
            get {
                return ResourceManager.GetString("InquiryNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry couldn&apos;t be marked as Resolved!.
        /// </summary>
        public static string InquiryNotResolved {
            get {
                return ResourceManager.GetString("InquiryNotResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry couldn&apos;t be Updated!.
        /// </summary>
        public static string InquiryNotUpdated {
            get {
                return ResourceManager.GetString("InquiryNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply couldn&apos;t be sent!.
        /// </summary>
        public static string InquiryReplyNotSent {
            get {
                return ResourceManager.GetString("InquiryReplyNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply sent to inquiry successfully..
        /// </summary>
        public static string InquiryReplySent {
            get {
                return ResourceManager.GetString("InquiryReplySent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry successfully Resolved..
        /// </summary>
        public static string InquiryResolved {
            get {
                return ResourceManager.GetString("InquiryResolved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inquiry successfully Updated..
        /// </summary>
        public static string InquiryUpdated {
            get {
                return ResourceManager.GetString("InquiryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid closing time in HH:MM format..
        /// </summary>
        public static string InvalidClosingTime {
            get {
                return ResourceManager.GetString("InvalidClosingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Credentials!.
        /// </summary>
        public static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a valid opening time in HH:MM format..
        /// </summary>
        public static string InvalidOpeningTime {
            get {
                return ResourceManager.GetString("InvalidOpeningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payment link!.
        /// </summary>
        public static string InvalidPaymentLink {
            get {
                return ResourceManager.GetString("InvalidPaymentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failed!.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login succeeded..
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t exceed more than 100 characters..
        /// </summary>
        public static string NameLength {
            get {
                return ResourceManager.GetString("NameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Activity found..
        /// </summary>
        public static string NoActivityFound {
            get {
                return ResourceManager.GetString("NoActivityFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Bookings Found!.
        /// </summary>
        public static string NoBookingsFound {
            get {
                return ResourceManager.GetString("NoBookingsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Category found..
        /// </summary>
        public static string NoCategoryFound {
            get {
                return ResourceManager.GetString("NoCategoryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Contacts Found!.
        /// </summary>
        public static string NoContactsFound {
            get {
                return ResourceManager.GetString("NoContactsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No contacts exist against provided group..
        /// </summary>
        public static string NoContactsInGroup {
            get {
                return ResourceManager.GetString("NoContactsInGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Country found!.
        /// </summary>
        public static string NoCountryFound {
            get {
                return ResourceManager.GetString("NoCountryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No County found..
        /// </summary>
        public static string NoCountyFound {
            get {
                return ResourceManager.GetString("NoCountyFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Email Template Found Against Provided Email Type..
        /// </summary>
        public static string NoEmailTemplateFound {
            get {
                return ResourceManager.GetString("NoEmailTemplateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inquiries found!.
        /// </summary>
        public static string NoInquiriesFound {
            get {
                return ResourceManager.GetString("NoInquiriesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Inquiry Found!.
        /// </summary>
        public static string NoInquiryFound {
            get {
                return ResourceManager.GetString("NoInquiryFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No record found..
        /// </summary>
        public static string NoRecordFound {
            get {
                return ResourceManager.GetString("NoRecordFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No State found!.
        /// </summary>
        public static string NoStateFound {
            get {
                return ResourceManager.GetString("NoStateFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Business has no subscription..
        /// </summary>
        public static string NoSubscription {
            get {
                return ResourceManager.GetString("NoSubscription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Table found against provided Template!.
        /// </summary>
        public static string NoTableFoundForTemplate {
            get {
                return ResourceManager.GetString("NoTableFoundForTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid state code!.
        /// </summary>
        public static string NotValidStateCode {
            get {
                return ResourceManager.GetString("NotValidStateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid US number!.
        /// </summary>
        public static string NotValidUSNumber {
            get {
                return ResourceManager.GetString("NotValidUSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Variables found against provided Table Id!.
        /// </summary>
        public static string NoVariablesFoundForTable {
            get {
                return ResourceManager.GetString("NoVariablesFoundForTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully..
        /// </summary>
        public static string PasswordChangedSuccessfully {
            get {
                return ResourceManager.GetString("PasswordChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is not correct!.
        /// </summary>
        public static string PasswordNotCorrect {
            get {
                return ResourceManager.GetString("PasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must contain atleast a number, a special character, and both lowercase and uppercase letters. Also, it&apos;s length must be of minimun 8 characters..
        /// </summary>
        public static string PasswordPattern {
            get {
                return ResourceManager.GetString("PasswordPattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while processing payment. Please check card details and try again.
        /// </summary>
        public static string PaymentFailed {
            get {
                return ResourceManager.GetString("PaymentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Payment Link was not sent.
        /// </summary>
        public static string PaymentLinkNotSent {
            get {
                return ResourceManager.GetString("PaymentLinkNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Link was sent Successfully!.
        /// </summary>
        public static string PaymentLinkSent {
            get {
                return ResourceManager.GetString("PaymentLinkSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t collect a payment because your email&apos;s limit is reached..
        /// </summary>
        public static string PaymentNotCollectedDueToEmailsLimit {
            get {
                return ResourceManager.GetString("PaymentNotCollectedDueToEmailsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t collect a payment because your sms limit is reached..
        /// </summary>
        public static string PaymentNotCollectedDueToSMSLimit {
            get {
                return ResourceManager.GetString("PaymentNotCollectedDueToSMSLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To collect more payments, please upgrade your package..
        /// </summary>
        public static string PaymentsLimitReached {
            get {
                return ResourceManager.GetString("PaymentsLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment processed successfully!.
        /// </summary>
        public static string PaymentSuccess {
            get {
                return ResourceManager.GetString("PaymentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records successfully inserted..
        /// </summary>
        public static string RecordsInserted {
            get {
                return ResourceManager.GetString("RecordsInserted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply Deleted Succesfully.
        /// </summary>
        public static string ReviewReplyDeleted {
            get {
                return ResourceManager.GetString("ReviewReplyDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to Delete Reply.
        /// </summary>
        public static string ReviewReplyDeleteFailed {
            get {
                return ResourceManager.GetString("ReviewReplyDeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong!.
        /// </summary>
        public static string ReviewReplyFailed {
            get {
                return ResourceManager.GetString("ReviewReplyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reply sent successfully!.
        /// </summary>
        public static string ReviewReplySuccessful {
            get {
                return ResourceManager.GetString("ReviewReplySuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Minutes must not be empty..
        /// </summary>
        public static string ServiceMinutesNotEmpty {
            get {
                return ResourceManager.GetString("ServiceMinutesNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To add more services, please upgrade your package..
        /// </summary>
        public static string ServicesLimitReached {
            get {
                return ResourceManager.GetString("ServicesLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message send failed.
        /// </summary>
        public static string SingleSMSNotSent {
            get {
                return ResourceManager.GetString("SingleSMSNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message was sent Succesfully.
        /// </summary>
        public static string SingleSMSSent {
            get {
                return ResourceManager.GetString("SingleSMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached the maximum limit. To send more sms, please upgrade your package..
        /// </summary>
        public static string SMSLimitReached {
            get {
                return ResourceManager.GetString("SMSLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Messages couldn&apos;t be sent!.
        /// </summary>
        public static string SMSNotSent {
            get {
                return ResourceManager.GetString("SMSNotSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All messages were sent Succesfully.
        /// </summary>
        public static string SMSSent {
            get {
                return ResourceManager.GetString("SMSSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No SMS Template Found.
        /// </summary>
        public static string SMSTemplateNotFound {
            get {
                return ResourceManager.GetString("SMSTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Template Types!.
        /// </summary>
        public static string TemplateTypesNotFound {
            get {
                return ResourceManager.GetString("TemplateTypesNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timezone must not be empty!.
        /// </summary>
        public static string TimezoneNotEmpty {
            get {
                return ResourceManager.GetString("TimezoneNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to perform this operation!.
        /// </summary>
        public static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is Unique..
        /// </summary>
        public static string UniqueUser {
            get {
                return ResourceManager.GetString("UniqueUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsyncing with Google Calendar succeeded..
        /// </summary>
        public static string UnsyncedWithGoogleCalendar {
            get {
                return ResourceManager.GetString("UnsyncedWithGoogleCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Email already exists!.
        /// </summary>
        public static string UserAlreadyExists {
            get {
                return ResourceManager.GetString("UserAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error! You cannot delete yourself!.
        /// </summary>
        public static string UserCannotDeleteItself {
            get {
                return ResourceManager.GetString("UserCannotDeleteItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully deleted..
        /// </summary>
        public static string UserDeleted {
            get {
                return ResourceManager.GetString("UserDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with email {{USER_EMAIL}} does not exist..
        /// </summary>
        public static string UserDoesNotExists {
            get {
                return ResourceManager.GetString("UserDoesNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can&apos;t login because your account is deactivated..
        /// </summary>
        public static string UserNotActive {
            get {
                return ResourceManager.GetString("UserNotActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User could not be created!.
        /// </summary>
        public static string UserNotCreated {
            get {
                return ResourceManager.GetString("UserNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User deleteion failed!.
        /// </summary>
        public static string UserNotDeleted {
            get {
                return ResourceManager.GetString("UserNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information could not be updated!.
        /// </summary>
        public static string UserNotUpdated {
            get {
                return ResourceManager.GetString("UserNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users successfully assigned to group..
        /// </summary>
        public static string UsersAssignedToGroup {
            get {
                return ResourceManager.GetString("UsersAssignedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users couldn&apos;t be assigned to group..
        /// </summary>
        public static string UsersNotAssignedToGroup {
            get {
                return ResourceManager.GetString("UsersNotAssignedToGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserType is invalid!.
        /// </summary>
        public static string UserTypeIdInvalid {
            get {
                return ResourceManager.GetString("UserTypeIdInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User information successfully updated..
        /// </summary>
        public static string UserUpdated {
            get {
                return ResourceManager.GetString("UserUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a valid booking time..
        /// </summary>
        public static string ValidBookingTime {
            get {
                return ResourceManager.GetString("ValidBookingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid payment link..
        /// </summary>
        public static string ValidPyamentLink {
            get {
                return ResourceManager.GetString("ValidPyamentLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website URL can&apos;t be empty..
        /// </summary>
        public static string WebsiteURLNotEmpty {
            get {
                return ResourceManager.GetString("WebsiteURLNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details added successfully..
        /// </summary>
        public static string WorkingDetailsAdded {
            get {
                return ResourceManager.GetString("WorkingDetailsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details deleted successfully..
        /// </summary>
        public static string WorkingDetailsDeleted {
            get {
                return ResourceManager.GetString("WorkingDetailsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details could not be added!.
        /// </summary>
        public static string WorkingDetailsNotAdded {
            get {
                return ResourceManager.GetString("WorkingDetailsNotAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details could not be deleted!.
        /// </summary>
        public static string WorkingDetailsNotDeleted {
            get {
                return ResourceManager.GetString("WorkingDetailsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details not found..
        /// </summary>
        public static string WorkingDetailsNotFound {
            get {
                return ResourceManager.GetString("WorkingDetailsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details could not be updated!.
        /// </summary>
        public static string WorkingDetailsNotUpdated {
            get {
                return ResourceManager.GetString("WorkingDetailsNotUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business Working Details updated successfully..
        /// </summary>
        public static string WorkingDetailsUpdated {
            get {
                return ResourceManager.GetString("WorkingDetailsUpdated", resourceCulture);
            }
        }
    }
}
